Domichamo/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('domicilio.urls')),
]

domicilio/urls.py
from django.urls import path
from . import views 

from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', views.signin, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.signout, name='logout'),
    path('parameters/categories', views.categories, name='categories'),
    path('parameters/measurement_units', views.measurement_units, name='measurement_units'),
    path('parameters/index/add_category', views.add_category, name='add_category'),
    path('parameters/index/edit_category', views.edit_category, name='edit_category'),
    path('parameters/index/delete_category', views.delete_category, name='delete_category'),
    path('parameters/index/add_measurement_unit', views.add_measurement_unit, name='add_measurement_unit'),
    path('parameters/index/edit_measurement_unit', views.edit_measurement_unit, name='edit_measurement_unit'),
    path('parameters/index/delete_measurement_unit', views.delete_measurement_unit, name='delete_measurement_unit'),
    path('elements/index', views.elements_index, name='elements.index'),
    path('elements/index/add_elements', views.add_elements, name='add_elements'),
    path('elements/index/edit_elements', views.edit_elements, name='edit_elements'),
    path('elements/index/delete_elements', views.delete_elements, name='delete_elements'),
    path('inventories/index', views.inventories_index, name='inventories.index'),   
    path('inventories/index/add_inventories', views.add_inventories, name='add_inventories'),
    path('inventories/index/edit_inventories', views.edit_inventories, name='edit_inventories'),
    path('inventories/index/delete_inventories', views.delete_inventories, name='delete_inventories'),
    path('domicilie', views.domicilie, name='domicilie'),
    path('save_domicilie', views.save_domicilie, name='save_domicilie'),
    path('my_domicilies/cancel', views.cancel, name='cancel'),
    path('domicilies/assign', views.assign_domicilies, name='assign_domicilies'),
    path('assign', views.assign, name='assign'),
    path('my_domicilies', views.my_domicilies, name='my_domicilies'),
    path('my_domicilies/complete', views.complete, name='complete'),
    path('my_domicilies/domicilies_user', views.domicilies_user, name='domicilies_user'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

domicilio/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class MeasurementUnits(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(verbose_name='name', null=False)
    abbreviation = models.TextField(verbose_name='abbreviation', null=False)

    def __str__(self):
        return self.name

class Categories(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(verbose_name='name', null=False)

    def __str__(self):
        return self.name

class Elements(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(verbose_name='Nombre', null=False)
    measurement_unit = models.ForeignKey(MeasurementUnits, on_delete=models.CASCADE)
    description = models.TextField(verbose_name='Descripción', null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', verbose_name='Imagen', null=True)

    def __str__(self):
        return self.name


class Inventories(models.Model):
    id = models.AutoField(primary_key=True)
    element = models.ForeignKey(Elements, on_delete=models.CASCADE)
    price = models.IntegerField(verbose_name='Precio', null=False, default=0)
    amount = models.IntegerField(verbose_name='Cantidad', null=False, default=0)
    stock = models.IntegerField(verbose_name='Stock', null=False, default=0)
    lot_number = models.IntegerField(verbose_name='Lote', null=True)
    expiration_date = models.DateField(verbose_name='Fecha de Expiración', null=True)
    user  = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.element.name

class Domicilies(models.Model):
    id = models.AutoField(primary_key=True)
    addres = models.TextField(null=False)
    date_time = models.DateTimeField(null=False)
    state = models.TextField(null=False)
    total = models.IntegerField(null=False, default=0)
    user  = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.addres

class AssignDomicilies(models.Model):
    id = models.AutoField(primary_key=True)
    domicilie  = models.ForeignKey(Domicilies, on_delete=models.CASCADE)    
    user  = models.ForeignKey(User, on_delete=models.CASCADE)
    
class DomicilieDetail(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(null=False)
    subtotal = models.IntegerField(null=False)
    inventory = models.ForeignKey(Inventories, on_delete=models.CASCADE)
    domicilie  = models.ForeignKey(Domicilies, on_delete=models.CASCADE)    
    user  = models.ForeignKey(User, on_delete=models.CASCADE)

domicilio/forms.py
from django import forms
from .models import MeasurementUnits, Categories, Elements, Inventories, Domicilies
from django.contrib.auth.models import User, Group

class AddElements(forms.Form):
    category_id = forms.ModelChoiceField(queryset=Categories.objects.all(), empty_label="Selecciona una categoría", widget=forms.Select(attrs={'class': 'form-control', 'name': 'category_id'}))
    measurement_unit_id = forms.ModelChoiceField(queryset=MeasurementUnits.objects.all(), empty_label="Selecciona una unidad de medida", widget=forms.Select(attrs={'class': 'form-control', 'name': 'measurement_unit_id'}))

class FormAddElements(forms.ModelForm):
    class Meta:
        model = Elements
        fields = ['name', 'description', 'image']
    def __init__(self, *args, **kwargs):
        super(FormAddElements, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

class FormEditElements(forms.ModelForm):
    class Meta:
        model = Elements
        fields = ['image']
    def __init__(self, *args, **kwargs):
        super(FormEditElements, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs['readonly'] = True
    
class AddInventory(forms.Form):
    element_id = forms.ModelChoiceField(queryset=Elements.objects.all(), empty_label="Selecciona un producto", widget=forms.Select(attrs={'class': 'form-control'}))

class FormAddInventory(forms.ModelForm):
    class Meta:
        model = Inventories
        fields = ['amount', 'stock', 'price', 'expiration_date', 'lot_number']

class Assign(forms.Form):
    domicilie_id = forms.ModelChoiceField(queryset=Domicilies.objects.all(), empty_label="Selecciona un domicilio", widget=forms.Select(attrs={'class': 'form-control'}), label="Domicilio")
    
    def __init__(self, *args, **kwargs):
        super(Assign, self).__init__(*args, **kwargs)

        # Filtra los usuarios por el grupo con ID 3
        group_id = 3  # Reemplaza con el ID de tu grupo específico
        self.fields['user_id'] = forms.ModelChoiceField(
            queryset=User.objects.filter(groups__id=group_id).distinct(),
            empty_label="Selecciona un usuario",
            widget=forms.Select(attrs={'class': 'form-control'}),
            label="Domiciliario"
        )

domicilio/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User, Group
from django.http import JsonResponse
from .models import Categories, MeasurementUnits, Elements, Inventories, Domicilies, DomicilieDetail, AssignDomicilies
from .forms import FormAddElements, FormEditElements, AddInventory, FormAddInventory, AddElements, Assign
from datetime import datetime, timedelta

# Create your views here.

def signin(request):
    if request.method == 'GET':
        return render(request, 'authentication/login.html')
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'authentication/login.html', {'error': 'Credenciales incorrectas'})
        else:
            login(request, user)
            if user.groups.filter(name='Administrador').exists():
                return redirect('categories')
            elif user.groups.filter(name='Domiciliario').exists():
                return redirect('my_domicilies')
            else:
                return redirect('domicilie')
                
        
def register(request):
    if request.method == 'GET':
        return render(request, 'authentication/register.html')
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], first_name=request.POST['first_name'], last_name=request.POST['last_name'], password=request.POST['password1'], email=request.POST['email'])
                
                # Asignar el usuario al grupo "Cliente"
                cliente_group, created = Group.objects.get_or_create(name='Usuario')
                user.groups.add(cliente_group)

                user.save()
                login(request, user)
                return redirect('login')
            except:
                return render(request, 'authentication/register.html', {'error': 'El usuario ya existe'})
        return render(request, 'authentication/register.html', {'error': 'No coinciden las contraseñas ingresadas'})

def signout(request):
    logout(request)
    return redirect('login')

def categories(request):
    categories = Categories.objects.all()
    title = 'Categorias'
    return render(request, 'parameters/categories/index.html', {'categories': categories, 'title': title})

def measurement_units(request):
    measurement_units = MeasurementUnits.objects.all()
    title = 'Unidades de medida'
    return render(request, 'parameters/measurement_unit/index.html', {'measurement_units': measurement_units, 'title': title})

def add_category(request):
    if request.method == 'POST':
        name = request.POST['name']
        if name:
            Categories.objects.create(name=name)
            # Puedes redirigir a una página de éxito o hacer lo que necesites aquí.
            return redirect('categories')  # Cambia 'exito' por la URL a la que deseas redirigir.
        # Si los datos del formulario no son válidos, puedes manejar los errores aquí.
    return render(request, 'parameters/categories/index.html')  # Cambia 'tu_template.html' por el nombre de tu plantilla modal.

def edit_category(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        name = request.POST.get('name')
        
        # Obtener el objeto de la categoría a editar
        category = get_object_or_404(Categories, id=category_id)
        
        # Actualizar los datos
        category.name = name
        category.save()
        
        # Redirigir al usuario a la página deseada, por ejemplo:
        return redirect('categories')
    else:
        return JsonResponse({'error': 'Método no permitido'})
    
def delete_category(request):
    if request.method == 'POST':
        category_id = request.POST.get('delete_category_id')
        
        # Obtener el objeto de la categoría a editar
        category = get_object_or_404(Categories, id=category_id)
        
        # Actualizar los datos
        category.delete()
        
        # Redirigir al usuario a la página deseada, por ejemplo:
        return redirect('categories')
    else:
        return JsonResponse({'error': 'Método no permitido'})


def add_measurement_unit(request):
    if request.method == 'POST':
        name = request.POST['name_measurement']
        abbreviation = request.POST['abbreviation']
        if name:
            unit = MeasurementUnits(
                name=name,
                abbreviation=abbreviation,
            )
            unit.save()
            # Puedes redirigir a una página de éxito o hacer lo que necesites aquí.
            return redirect('measurement_units')  # Cambia 'exito' por la URL a la que deseas redirigir.
        # Si los datos del formulario no son válidos, puedes manejar los errores aquí.
    return render(request, 'parameters/measurement_unit/index.html')  # Cambia 'tu_template.html' por el nombre de tu plantilla modal.

def edit_measurement_unit(request):
    if request.method == 'POST':
        measurement_unit_id = request.POST.get('measurement_unit_id')
        name = request.POST.get('name_measurement')
        abbreviation = request.POST.get('abbreviation')
        
        # Obtener el objeto de la categoría a editar
        measurement_unit = get_object_or_404(MeasurementUnits, id=measurement_unit_id)
        
        # Actualizar los datos
        measurement_unit.name = name
        measurement_unit.abbreviation = abbreviation

        measurement_unit.save()
        
        # Redirigir al usuario a la página deseada, por ejemplo:
        return redirect('measurement_units')
    else:
        return JsonResponse({'error': 'Método no permitido'})
    
def delete_measurement_unit(request):
    if request.method == 'POST':
        measurement_unit_id = request.POST.get('delete_measurement_unit_id')
        
        # Obtener el objeto de la categoría a editar
        measurement_unit = get_object_or_404(MeasurementUnits, id=measurement_unit_id)
        
        # Actualizar los datos
        measurement_unit.delete()
        
        # Redirigir al usuario a la página deseada, por ejemplo:
        return redirect('measurement_units')
    else:
        return JsonResponse({'error': 'Método no permitido'})

def elements_index(request):
    form = AddElements()
    formulario = FormAddElements(request.POST or None)
    formularioEdit = FormEditElements(request.POST or None)
    elements = Elements.objects.all()
    categories = Categories.objects.all()
    measurement_units = MeasurementUnits.objects.all()
    title = 'Productos'
    return render(request, 'elements/index.html', {'form': form, 'formulario': formulario, 'formularioEdit': formularioEdit ,'elements': elements, 'categories': categories, 'measurement_units': measurement_units, 'title': title})

def add_elements(request):
    if request.method == 'POST':
        formulario = FormAddElements(request.POST or None, request.FILES or None)
        if formulario.is_valid():
            element = formulario.save(commit=False)
            category_id = request.POST['category_id']
            measurement_unit_id = request.POST['measurement_unit_id']
            user_id = request.user.id

            element.category_id = category_id
            element.measurement_unit_id = measurement_unit_id
            
            element.save()
            # Puedes redirigir a una página de éxito o hacer lo que necesites aquí.
            return redirect('elements.index')  # Cambia 'exito' por la URL a la que deseas redirigir.
        # Si los datos del formulario no son válidos, puedes manejar los errores aquí.
    else:
        formulario = FormAddElements()
    return render(request, 'elements/index.html')  # Cambia 'tu_template.html' por el nombre de tu plantilla modal.

def edit_elements(request):
    element_id = request.POST.get('element_id')
    if request.method == 'POST':
        id = get_object_or_404(Elements, id=element_id)
        form = FormEditElements(request.POST, request.FILES, instance=id)
        if form.is_valid():
            element = form.save(commit=False)
            name = request.POST.get('name')
            description = request.POST.get('description')
            price = request.POST.get('price')
            category_id = request.POST.get('category_id')
            measurement_unit_id = request.POST.get('measurement_unit_id')
            
            # Actualizar los datos
            element.name = name
            element.description = description
            element.price = price
            element.category_id = category_id
            element.measurement_unit_id = measurement_unit_id
            element.save()
        
            # Redirigir al usuario a la página deseada, por ejemplo:
            return redirect('elements.index')
    else:
        return JsonResponse({'error': 'Método no permitido'})

def delete_elements(request):
    if request.method == 'POST':
        element_id = request.POST.get('element_id')
        
        # Obtener el objeto de la categoría a editar
        element = get_object_or_404(Elements, id=element_id)
        
        # Actualizar los datos
        element.delete()
        
        # Redirigir al usuario a la página deseada, por ejemplo:
        return redirect('elements.index')
    else:
        return JsonResponse({'error': 'Método no permitido'})
    
def inventories_index(request):
    form = AddInventory()
    formulario = FormAddInventory(request.POST or None)
    data = Inventories.objects.all()
    elements = Elements.objects.all()
    title = 'Inventario'
    return render(request, 'inventories/index.html', {'form': form, 'formulario': formulario, 'data': data, 'elements': elements, 'title': title})

def add_inventories(request):
    if request.method == 'POST':

domicilio/templates/user/add_domicilie.html
{% extends "base.html" %}

{% block content %}


<form action="{% url 'save_domicilie' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="hidden" name="date_time" value="{{ datetime }}">
    <div class="total" style="margin: 4px;">
        <div class="row">
            <div class="col-md-3">
                <label for="addres">Dirección</label>
                <input type="text" class="form-control" name="addres" id="addres" required>
            </div>
            <div class="col-md-3" style="position: relative; top: 32px;">
                <span id="total"></span>
                <button type="submit" class="btn btn-success">Pedir</button>
            </div>
        </div>
        <br>
    </div>

    <div class="container" style="margin: 40px;">
        <div class="row">
            {% for i in inventories %}
            <div class="col">   
                <div class="card" style="width: 18rem;">
                    <img src="{{i.element.image.url}}" class="card-img-top" height="150" width="100">
                    <div class="card-body">
                        <h5 class="card-title"><strong>{{i.element.name}}</strong></h5>
                        <p class="card-text"><strong>Disponible:</strong> {{i.amount}} <br> <strong>Precio:</strong> {{i.price}} <br> <strong>Fecha de expidición: </strong>{{i.expiration_date}}</p>
                        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#domicilie{{i.id}}">
                            <i class="fas fa-plus" style="color: #00ff11;"></i> Pedir
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="domicilie{{ i.id }}" tabindex="-1" aria-labelledby="domicilie{{ i.id }}Label" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="domicilieLabel">Pedir {{i.element.name}}</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    
                                    <div class="modal-body">
                                        {% if i %}
                                        <input type="hidden" name="products[]" value="{{ i.id }}">
                                        {% endif %}
                                        <label for="amount">Cantidad</label>
                                        <input type="number" class="form-control" name="amount[]" id="amount">
                                        <label for="subtotal">Subtotal</label>
                                        <input type="number" class="form-control" name="subtotal[]" id="subtotal" readonly>
                                        <input type="hidden" class="form-control" id="price_unit" value="{{ i.price }}">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                        <button type="button" class="btn btn-success" id="guardar-btn" data-bs-dismiss="modal">Guardar</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</form>

<script>
    const guardarBtns = document.querySelectorAll('#guardar-btn');
    guardarBtns.forEach(function (button) {
        button.addEventListener('click', function () {
            const cardElement = button.closest('.card'); // Get the card element associated with the button
            const cantidadElement = cardElement.querySelector('#amount'); // Get the amount input element
            const cantidad = parseInt(cantidadElement.value, 10);
            const productId = button.dataset.productId; // Get the product ID from the button's data attribute

            // Store the quantity in a variable
            const quantityToDisplay = cantidad;

            // Create the floating text element
            const quantityElement = document.createElement('div');
            quantityElement.classList.add('floating-text');
            quantityElement.textContent = `Cantidad: ${quantityToDisplay}`;

            // Position the floating text element
            quantityElement.style.position = 'absolute';
            quantityElement.style.top = 0;
            quantityElement.style.right = 0;
            quantityElement.style.backgroundColor = '#f2f2f2';
            quantityElement.style.padding = '5px 10px';
            quantityElement.style.border = '1px solid #ccc';
            quantityElement.style.borderRadius = '5px';
            quantityElement.style.zIndex = 1;

            // Append the floating text element to the card
            cardElement.appendChild(quantityElement);
        });
    });


    $(document).ready(function() {
        $('.modal-body').on('input', 'input#amount', function() {
            updateSubTotalPrice(); // Actualizar el precio total cuando se modifica la cantidad
        });

        function updateSubTotalPrice() {
                var isValid = true;
                $('.modal-body').each(function() {
                    var priceField = $(this).find('input#price_unit').val();
                    var price = parseFloat(priceField) || 0;
                    var amountField = $(this).find('input#amount').val();
                    var amount = parseFloat(amountField) || 0;
        
                    var totalField = $(this).find('input#subtotal');
                    var subtotal = price * amount;
                    totalField.val(subtotal);

                });
                updateTotalPrice(); // Actualiza el campo de Total con el valor calculado
            }

            function updateTotalPrice() {
                var totalPrice = 0;
                $('.modal-body').each(function() {
                    var totalField = $(this).find('input#subtotal');
                    var subtotal = parseFloat(totalField.val()) || 0;
                    totalPrice += subtotal;
                    console.log(totalPrice);
                });
                // Actualiza el campo de Total con el valor calculado
                $('#total').text('Total: ' + totalPrice);
            }
    });
</script>
{% endblock %}

domicilio/templates/user/domicilies.html
{% extends "base.html" %}

{% block content %}

<div class="domicilies" style="margin: 20px;">
    <h2>Mis Domicilios</h2>
    <table id="domicilies" class="table table-striped" style="width: 100%;">
        <thead>
            <tr>
                <th>Fecha y Hora</th>
                <th>Productos pedidos</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
                <th>Total</th>
                <th>Estado</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for d in domicilies %}
            <tr>
                <td>{{d.date_time}}</td>
                <td>
                    {% for detail in d.domiciliedetail_set.all %}
                    {{detail.inventory.element.name}}<br>
                    {% endfor %}
                </td>
                <td>
                    {% for detail in d.domiciliedetail_set.all %}
                        {{ detail.amount }}<br>
                    {% endfor %}
                </td>
                <td>
                    {% for detail in d.domiciliedetail_set.all %}
                        {{detail.subtotal}}<br>
                    {% endfor %}
                </td>
                <td>{{d.total}}</td>
                <td>{{d.state}}</td>
                <td>
                    {% if d.state == 'En proceso' %}
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#cancel_domicilie{{ d.id }}"><i class="fas fa-times"></i></button>
                    <div class="modal fade" id="cancel_domicilie{{ d.id }}" tabindex="-1" aria-labelledby="cancel_domicilie{{ d.id }}Label" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="cancel_domicilieLabel">Cancelar Domicilio</h1>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <form action="{% url 'cancel' %}" method="post">
                                        {% csrf_token %}
                                        <div class="modal-body">
                                            {% if d %}
                                            <input type="hidden" name="domicilie" value="{{ d.id }}">
                                            {% endif %}
                                            <p>¿Deseas cancelar el domicilio?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                            <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Sí, cancelar</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}